name: Publish NuGet Package

on:
  push:
    branches:
      - release/*
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish to NuGet
    runs-on: ubuntu-latest
    permissions:
      id-token: write # enable GitHub OIDC token issuance for this job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack NuGet package
      run: dotnet pack ReplaceObsolete.Package/ReplaceObsolete.Package.csproj --configuration Release --no-build --output ./artifacts

    - name: Nuget Login (OIDC + temp API Key)  
      uses: Nuget/login@v1
      id: login
      with:
        user: ${{secrets.NUGET_USER}}

    - name: Nuget push
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
        
    - name: Done
      run: echo "Package published successfully!"
